# Generated by Django 5.0.1 on 2024-02-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='Likes',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
