# Generated by Django 5.0.1 on 2024-02-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='image',
        ),
    ]
